### ISSUE TITLE
Bedenk een Epic

### ISSUE THREAD

**Issue by SamaraFellaDina** [SamaraFellaDina/lose-your-head-the-client-case#10]

**Comment by Khdulkadir** [comment]
Ontwikkel een detail pagina van een automatische toegankelijkheid scan voor de AccessDash web applicatie. Op deze pagina zijn meerdere inzichten in te zien. Zoals de totaalscore van de toegankelijkheid van de pagina en de verschillende soorten errors op de pagina.
