### ISSUE TITLE
Browsertest

### ISSUE THREAD

**Issue by SamaraFellaDina** [SamaraFellaDina/lose-your-head-the-client-case#110]
Kijk via browserstack of alles egaal loopt

**Comment by Khdulkadir** [comment]
Firefox, alles werkt goed: 

![Image](https://github.com/user-attachments/assets/cf17cf82-19db-4964-b3ae-6d1d34e433ba)

Safari, alles werkt goed:

![Image](https://github.com/user-attachments/assets/06fc4c3d-f699-4a7b-a1b3-b89bc831647f)

Edge, alles werkt goed:

![Image](https://github.com/user-attachments/assets/6b3ddd0d-88bb-44c2-b96d-9230384b3ffe)

Chrome, zonder javascript, alles werkt goed en progressive enhanced:

![Image](https://github.com/user-attachments/assets/c484f45b-c1fc-44ca-9863-bda204be94d1)

Chrome oude versie 76, grafieken werken niet en backupdata ook niet:

![Image](https://github.com/user-attachments/assets/0c6b1026-65aa-4d5c-8093-bf161ca91a27)
