### ISSUE TITLE
Code/design review {Team Triple]

### ISSUE THREAD

**Issue by driezie** [SamaraFellaDina/lose-your-head-the-client-case#21]
## Projectboard

Je hebt een goeie project board opgezet. Je kan goed zien wat je prioriteit is en hoe lastig/effort je nodig hebt voor deze opdracht. Onthoud dat als een planning poker over de 10 gaat dat je heel misschien meerdere issues moet gebruiken om dit te moeten oplossen. 

Probeer alle issues ook een beetje te verdelen zodat niet iedereen allemaal hetzelfde issue doet :)

**Comment by SamaraFellaDina** [comment]
Hee! Bedankt voor de feedback :) We moeten ook zeker nog kijken naar planning poker 
* #14 

Nemen dit zeker mee!

![](https://media2.giphy.com/media/v1.Y2lkPTc5MGI3NjExZ2c5Z3R4cTlpdXAydDdod3dtc3VtdG1tZHdwNGVqdjFmcmZxOHo5MyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/tHIRLHtNwxpjIFqPdV/giphy.webp)
