### ISSUE TITLE
global css aanpassen

### ISSUE THREAD

**Issue by J3SS3HVA** [SamaraFellaDina/lose-your-head-the-client-case#41]
Ik heb naar de global.css gekeken. alleen kom ik een paar probleempjes tegen wanneer ik in de main page.svelte werk.

https://github.com/SamaraFellaDina/lose-your-head-the-client-case/blob/6c8a7bfcdc325d889d86d54bc591d87f73d01a29/static/styles/global.css#L28-L32

in het `*` element heb je dus voor alle elementen die geen background-color propertie hebt het volgende mee gegeven.

dit is niet fijn want de content in elke section krijgt dan de zelfde background als de body.

hier is een voorbeeld de content is wel gewoon in de section maar door het `*` element pakt hij dezelfde background color als de body.
![section example](https://github.com/user-attachments/assets/59d78c1f-1f32-4d2f-a16a-3167f128f42e)

**verander het volgende**

haal die background proportie weg uit het `*` element en zet hem in de body.

en probeer zo veel mogelijk aangemaakte custom properties in de route te doen als dat mogelijk is

**Comment by J3SS3HVA** [comment]
note: sammy heeft deze issue gefixed

**Comment by SamaraFellaDina** [comment]
Hii! Ik ga zelf vandaag nog even kijken welke stijling verbeterd kan worden, om dat zoveel mogelijk overeen te laten komen met het originele design

**Comment by SamaraFellaDina** [comment]
Hii! Ik ga zelf vandaag nog even kijken welke stijling verbeterd kan worden, om dat zoveel mogelijk overeen te laten komen met het originele design

**Comment by SamaraFellaDina** [comment]
Volgens @Khdulkadir 
* moet ik de regular & medium veranderen naar "outfit".
* Bij custom properties hoef je maar een font family aan te maken.
