### ISSUE TITLE
Tab test

### ISSUE THREAD

**Issue by SamaraFellaDina** [SamaraFellaDina/lose-your-head-the-client-case#63]

**Comment by Khdulkadir** [comment]
Ik heb een tabtest gedaan op de website. Er zijn bijna geen interactieve elementen op de website waardoor er weinig getabt kan worden. Er zijn wel een aantal buttons waar correct doorheen getabt kan worden:

![Image](https://github.com/user-attachments/assets/9b085bbb-14ba-4d80-a28c-b02b23e64163)
