### ISSUE TITLE
Opmerking over Readme bestand

### ISSUE THREAD

**Issue by TygoWolven** [SamaraFellaDina/lose-your-head-the-client-case#81]
## Missende informatie
Ik zie dat jullie een goed begin hebben gemaakt in de Readme, echter missen er nog wel een aantal dingen. Denk hierbij aan de volgende punten:
- Design / Website screenshots
- Beschrijving van de website

### Screenshots
Screenshots in de Readme die laten zien hoe de pagina er uit ziet zorgen voor een globaal overzicht van waar jullie mee bezig zijn. Als je bij die screenshots nog een keer de live-link zet kunnen de lezers ook snel de site bekijken..

### Beschrijving
Ook is er niet beschreven wat het doel is van de website, dus als ik op basis van de Readme moet gaan raden waar jullie mee bezig zijn wordt dat heel lastig. Probeer een beschrijving te geven van de pagina zodat voor iedereen duidelijk is waar het over gaat, en wat het doel is van de pagina.

**Comment by SamaraFellaDina** [comment]
Thanks! We gaan er naar kijken
